### ISSUE TITLE
Cannot find module webpack from next-plugin.mjs

### ISSUE THREAD

**Issue by BenjaminLesne** [BuilderIO/hydration-overlay#16]
- I installed the package:
```bash
pnpm install @builder.io/react-hydration-overlay
```

- I updated the root of my app like this:

<details>
<summary>click to expand</summary>
<div>

```ts
// file: _app.tsx
/*
...
imports
...
*/
import { HydrationOverlay } from "@builder.io/react-hydration-overlay";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <HydrationOverlay>
      <Head>
        <title>{BRAND_NAME}</title>
      </Head>
      <Component {...pageProps} />
    </HydrationOverlay>
  );
};

export default api.withTRPC(MyApp);

```
</div>
</details>

- I updated my next config like this:
<details>
<summary>click to expand</summary>

```ts
// file: next.config.mjs
import { withHydrationOverlay } from "@builder.io/react-hydration-overlay/next";
/**
 * Run `build` or `dev` with `SKIP_ENV_VALIDATION` to skip env validation. This is especially useful
 * for Docker builds.
 */
await import("./src/env.mjs");

/** @type {import("next").NextConfig} */
const config = {
  reactStrictMode: true,

  /**
   * If you have `experimental: { appDir: true }` set, then you must comment the below `i18n` config
   * out.
   *
   * @see https://github.com/vercel/next.js/issues/41980
   */
  i18n: {
    locales: ["fr"],
    defaultLocale: "fr",
  },

  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  swcMinify: true,
};

export default withHydrationOverlay()(config);
```
</details>

-  I run 
```bash
pnpm dev
```

# Current behavior
My terminal throws this error:

```bash
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /home/benjamin/code/jegwell-t3/.env
- error Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/benjamin/code/jegwell-t3/node_modules/.pnpm/@builder.io+react-hydration-overlay@0.0.5_react-dom@18.2.0_react@18.2.0/node_modules/@builder.io/react-hydration-overlay/dist/webpack' imported from /home/benjamin/code/jegwell-t3/node_modules/.pnpm/@builder.io+react-hydration-overlay@0.0.5_react-dom@18.2.0_react@18.2.0/node_modules/@builder.io/react-hydration-overlay/dist/next-plugin.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:224:11)
    at moduleResolve (node:internal/modules/esm/resolve:837:10)
    at defaultResolve (node:internal/modules/esm/resolve:1035:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:269:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:153:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  type: 'Error',
  code: 'ERR_MODULE_NOT_FOUND'
}
 ELIFECYCLE  Command failed with exit code 1.
```

# Expected behavior
My app start without errors

# Additionnal info

- my package.json:

<details>
<summary>click to expand</summary>

```json
{
  "name": "jegwell-t3",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "postinstall": "prisma generate",
    "lint": "next lint",
    "typecheck": "tsc --noEmit",
    "start": "next start",
    "test:e2e": "playwright test",
    "test:e2e:local": "playwright test --headed --project='Mobile Chrome'",
    "test:e2e:local-ui": "playwright test --ui",
    "test:e2e:snapshots": "playwright test --update-snapshots",
    "stripe:listen": "stripe listen --forward-to localhost:3000/api/stripe",
    "stripe:trigger": "stripe trigger payment_intent.succeeded"
  },
  "dependencies": {
    "@builder.io/react-hydration-overlay": "^0.0.5",
    "@clerk/nextjs": "^4.17.1",
    "@fontsource/roboto": "^4.5.8",
    "@hookform/resolvers": "^3.1.1",
    "@prisma/client": "^4.11.0",
    "@radix-ui/react-alert-dialog": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-dropdown-menu": "^2.0.5",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-radio-group": "^1.1.3",
    "@radix-ui/react-select": "^1.2.2",
    "@radix-ui/react-slot": "^1.0.2",
    "@stripe/stripe-js": "^1.54.1",
    "@t3-oss/env-nextjs": "^0.2.1",
    "@tanstack/react-query": "^4.28.0",
    "@tanstack/react-table": "^8.9.3",
    "@trpc/client": "^10.18.0",
    "@trpc/next": "^10.18.0",
    "@trpc/react-query": "^10.18.0",
    "@trpc/server": "^10.18.0",
    "class-variance-authority": "^0.6.0",
    "clsx": "^1.2.1",
    "cmdk": "^0.2.0",
    "lucide-react": "^0.224.0",
    "micro": "^10.0.1",
    "next": "^13.4.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.45.2",
    "react-slick": "^0.29.0",
    "stripe": "^12.16.0",
    "superjson": "1.12.2",
    "tailwind-merge": "^1.12.0",
    "tailwindcss-animate": "^1.0.5",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@playwright/test": "^1.36.2",
    "@types/eslint": "^8.21.3",
    "@types/node": "^18.15.5",
    "@types/prettier": "^2.7.2",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@types/react-slick": "^0.23.10",
    "@typescript-eslint/eslint-plugin": "^5.56.0",
    "@typescript-eslint/parser": "^5.56.0",
    "@vitejs/plugin-react": "^4.0.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.36.0",
    "eslint-config-next": "^13.4.1",
    "jsdom": "^22.0.0",
    "postcss": "^8.4.21",
    "prettier": "^2.8.6",
    "prettier-plugin-tailwindcss": "^0.2.6",
    "prisma": "^5.1.1",
    "tailwindcss": "^3.3.0",
    "typescript": "^5.0.2",
    "vitest": "^0.31.1"
  },
  "ct3aMetadata": {
    "initVersion": "7.12.2"
  }
}
```
</details>

- I tried using the Webpack helper, it gave me a similar error

<details>
<summary>click to expand</summary>

```bash
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /home/benjamin/code/jegwell-t3/.env
- error Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'webpack' imported from /home/benjamin/code/jegwell-t3/node_modules/.pnpm/@builder.io+react-hydration-overlay@0.0.5_react-dom@18.2.0_react@18.2.0/node_modules/@builder.io/react-hydration-overlay/dist/webpack.mjs
Did you mean to import webpack/webpack-lib.js?
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:781:9)
    at moduleResolve (node:internal/modules/esm/resolve:830:20)
    at defaultResolve (node:internal/modules/esm/resolve:1035:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:269:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:153:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  type: 'Error',
  code: 'ERR_MODULE_NOT_FOUND'
}
 ELIFECYCLE  Command failed with exit code 1.
```
</details>

- My IDE could not auto import withHydrationOverlay somehow, ts complains that the module does not exist.

Did I miss something?

PS: As a maintainer, is it better to have those "click to expand" or should I remove them next time?

# Video

https://github.com/BuilderIO/hydration-overlay/assets/73464907/a7785582-b931-4231-928a-2fe79670c0b9

**Comment by JohnRPB** [comment]
This is technically a duplicate of [https://github.com/BuilderIO/hydration-overlay/issues/15](my post) except you did a **far** better job at documenting your issue. As I mentioned in my post, the issue arises because of an explicit dependency on webpack, whereas the best practice with NextJS now  is to use webpack plugins through the webpack helper instance in the config file, not to install webpack directly.

**Comment by BenjaminLesne** [comment]
> If the maintainer can update the wrapper function to optionally accept a webpack instance, it will solve our problem.

@JohnRPB it seems like you know what you are doing, could you make a PR fixing this?

If not:
I suppose all we have to do is get rid of the webpack import in next-plugin.mjs and use the webpack given as an argument to the withHydrationOverlayWebpack function?

I never did that before so if you have any material that could help me to do this feel free to share it

**Comment by BenjaminLesne** [comment]
I tried to fix this with the last brain cells I had after work.
Here is what I manage to understand:

- We need to use the Webpack helper and pass as an optional argument the webpack given by the nextjs config file (see [line 4 of the first block of code here](https://nextjs.org/docs/app/api-reference/next-config-js/webpack)) to the `withHydrationOverlayWebpack` function.

- If no argument are given we use the webpack imported at the top of the file I suppose?. (this is the current behavior)

- The `next-plugin.ts` file use the `withHydrationOverlayWebpack`.
We need to update it to make it use the webpack given as argument instead of the imported webpack at the top of the file.

- I did that, build the library, added to my nextjs project. It somehow managed to start the dev server but did not show the overlay showing the Hydration Errors. I might have missed something.

It's getting late I will continue this an other day. :sleeping:

**Comment by max-programming** [comment]
Not sure if this happens to everyone. 
I use `next.config.mjs` and it happened to me so I guess this happens to everyone using `mjs`

**Comment by dBianchii** [comment]
Happening with me. I use .js and a package.json with `type: module`.

![image](https://github.com/BuilderIO/hydration-overlay/assets/17372417/642a006f-535a-433e-9299-2f4a4a85539e)
```ts
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/gabriel/Documents/Github/kodix-turbo/node_modules/@builder.io/react-hydration-overlay/dist/webpack' imported from /home/gabriel/Documents/Github/kodix-turbo/node_modules/@builder.io/react-hydration-overlay/dist/next-plugin.mjs
@kdx/kdx:dev:     at finalizeResolution (node:internal/modules/esm/resolve:255:11)
@kdx/kdx:dev:     at moduleResolve (node:internal/modules/esm/resolve:908:10)
@kdx/kdx:dev:     at defaultResolve (node:internal/modules/esm/resolve:1121:11)
@kdx/kdx:dev:     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
@kdx/kdx:dev:     at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
@kdx/kdx:dev:     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
@kdx/kdx:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
@kdx/kdx:dev:     at link (node:internal/modules/esm/module_job:84:36) {
@kdx/kdx:dev:   code: 'ERR_MODULE_NOT_FOUND',
@kdx/kdx:dev:   url: 'file:///home/gabriel/Documents/Github/kodix-turbo/node_modules/@builder.io/react-hydration-overlay/dist/webpack'
@kdx/kdx:dev: }
@kdx/kdx:dev: 
@kdx/kdx:dev: Node.js v20.10.0
```

**Comment by samijaber** [comment]
Should be fixed in https://github.com/BuilderIO/hydration-overlay/releases/tag/%40builder.io%2Freact-hydration-overlay%400.0.6

**Comment by JohnRPB** [comment]
So I'm still getting the exact same error from before: "Cannot find package 'webpack' imported from ~/path_to_my_project/node_modules/@builder.io/react-hydration-overlay/dist/webpack.mjs"

I look and see that the webpack.mjs file imports 'webpack' as a dependency.

**Comment by BenjaminLesne** [comment]
@JohnRPB upgrading to 0.0.6 fixed the webpack error I had. I did not use the webpack helper, I used the withHydrationOverlay function in my config file of my nextjs app (I don't use the App router).

Do you have more info related to your setup? or even steps to reproduce it?
